// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB35MUzjQOQiE3IRbfrf-MiXyRCLyJ77U',
    appId: '1:368910135877:web:b636511d5fff40cb6ee92c',
    messagingSenderId: '368910135877',
    projectId: 'dhyan-7c55d',
    authDomain: 'dhyan-7c55d.firebaseapp.com',
    storageBucket: 'dhyan-7c55d.firebasestorage.app',
    measurementId: 'G-ZQR0QXTFMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWc3e5BZI89LEbtxhEeMx-yQJiRf6AzLY',
    appId: '1:368910135877:android:4166b9160e347a3a6ee92c',
    messagingSenderId: '368910135877',
    projectId: 'dhyan-7c55d',
    storageBucket: 'dhyan-7c55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Cm5frhbXyH3RSiLrZ582_vF-DaYTdDM',
    appId: '1:368910135877:ios:a7a7b20d5845ca8e6ee92c',
    messagingSenderId: '368910135877',
    projectId: 'dhyan-7c55d',
    storageBucket: 'dhyan-7c55d.firebasestorage.app',
    iosBundleId: 'com.dhyanlife.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Cm5frhbXyH3RSiLrZ582_vF-DaYTdDM',
    appId: '1:368910135877:ios:544e1199f13009406ee92c',
    messagingSenderId: '368910135877',
    projectId: 'dhyan-7c55d',
    storageBucket: 'dhyan-7c55d.firebasestorage.app',
    iosBundleId: 'com.example.meditationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB35MUzjQOQiE3IRbfrf-MiXyRCLyJ77U',
    appId: '1:368910135877:web:f17959b9c4bd7edf6ee92c',
    messagingSenderId: '368910135877',
    projectId: 'dhyan-7c55d',
    authDomain: 'dhyan-7c55d.firebaseapp.com',
    storageBucket: 'dhyan-7c55d.firebasestorage.app',
    measurementId: 'G-HFRT6D2D83',
  );
}
